title: Oracle Developer Relations
email: devrel-opensource_ww@oracle.com
description: >-
  The Oracle Developer Relations team.  Helping you to be awesome 
  while doing cool stuff.
baseurl: "" # the subpath of your site, e.g. /blog
domain: oracle-devrel.github.io
url: https://oracle-devrel.github.io
# twitter_username: jekyllrb
# github_username: oracle-devrel
# slack_workspace: oracledevrel-learn
# Build settings
# remote_theme: pages-themes/slate@v0.2.0
theme: minima
# theme: slate
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

header_pages:
  - about.md
  - publishing/index.md
  - publishing/working_with_repos.md
header_links:
  -
    img: /assets/images/DevRel_Logo.png
    img_alt: Oracle Developer Relations Logo
    url: /
    style: "width: 30px; height: 30px;"
  - 
    title: Dev.O
    url: https://developer.oracle.com
  - 
    title: Repositories
    url: https://github.com/orgs/oracle-devrel/repositories
  
minima:
  social_links:
    github: oracle-devrel
    slack: oracledevrel-learn
